#!/bin/bash
#SBATCH -n 40
#SBATCH -N 1
#SBATCH --mem 200G
#SBATCH --time 24:0:0
#SBATCH --mail-type ALL
#SBATCH --account= account name

# Stop script if any command fails
set -e

# Load necessary modules
module purge
module load bluebear
module load FastQC/0.11.9-Java-11

# Navigate  directory
cd /rds/projects/m/mcgetthm-monocytes-ageing/RNA_seq/20220803_Aged_F_mice/FastQC/

# Run FastQC on all fastq.gz files- thread 40
for f in *.fastq.gz; do
    fastqc -o ./ -t 40 "$f"
done

# Load MultiQC module
module load MultiQC/1.9-foss-2019b-Python-3.7.4

# Run MultiQC to aggregate FastQC reports
multiqc .

